# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d68d00aa384ef63694cb7ef0d2f5e57752911c139e84df7118378bb490e2769756237685a3cd6ae173b9600b34b83b45f43cc9e24998862931b01edfa30f9dc4

test:
  secret_key_base: 834efe33c1f7e7e1f9a3e94372859ff07eaea9f18ecfde09ef007c342d3c0a8e9e8251146e7b33eccbd957a756b96ff1371eccf6a2be76f4550da6e9a7a42219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
