# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69913b2441273946aec5740862903ff8849aeaa7dba7d25f18f0075c0092eae33f96946376f06377f5afe7ad13b2513da46b036ff29253db9ea405efa753e50

test:
  secret_key_base: 8d2d285a07bb2cf9ba784ccb69f7177af1a4401db11f4fa4ec388950d8304b773577ca8a60a5ef6bb4c48a666b60b8f9ffd1c64f4bd51f660a7960640f27f4a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
